# -*- coding: utf-8 -*-
"""Week_01_F13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12taFMBdEF_dmg0bymXuTlGin1siBdL1d
"""

print("Hello")

value =10
name="ALI"
cgpa=2.5
status=True


print(name)

print(type(name))

print(type(status))

age = int(input("Enter your age "))
print(age)

print(age+5)

num =10

if num>0:
  print("Positive")
  if(num%2==0):
    print("EVEN")
elif(num==0)
  print("ZERO")
else:
  print("Negative")

# for(int I=0;I<10;I++){

# }

for i in range(10):
  print(i,end=" ")

for i in range(2,10):
  print(i,end=" ")

for i in range(2,20,3):
  print(i,end=" ")

for i in range(20,2,-1):
  print(i,end=" ")

x=10

while(x>0):
  print(x,end=" ")
  x=x-1

def Sum(a,b):
  return a+b

Sum(9,4)

with open('hello.txt','w') as file:
  file.write("This is me Afham NAzir")

with open('hello.txt','r') as file:
  res= file.read()
  print(res)

arr=[1,2,3,4,5,6,7,8,9,10,'UCP',2.5,False,10,20,30,1,2]
print(arr)

for i in arr:
  print(i,end=" ")

print(dir(arr))

# print(help(arr))

print(arr)

arr.append(100)
arr.insert(2,200)
arr.extend(["A","B","C"])

print(arr)